name: Node.js CI

on:
  push:
    branches: [ "main", "master" ] # Kích hoạt workflow khi có push lên nhánh main hoặc master
  pull_request:
    branches: [ "main", "master" ] # Kích hoạt workflow khi có pull request vào nhánh main hoặc master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Kiểm tra sự tồn tại của package-lock.json
      run: |
        if [ -f package-lock.json ]; then
          echo "package-lock.json exists.";
        else
          echo "package-lock.json does not exist. Generating one.";
          npm install --package-lock-only;
        fi

    - name: Install dependencies if npm ci fails
      run: npm ci || npm install

    - name: List installed packages
      run: npm list

    - name: Run tests
      run: npm test
