name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # Xem lịch phát hành Node.js tại https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Sử dụng Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: node -v # Kiểm tra phiên bản Node.js đang sử dụng
    - run: npm ci
    - run: npm list # In ra danh sách các gói và phiên bản đang được sử dụng
    - run: npm test
